server:
  port: 8090
spring:
  datasource:
    dynamic:
      p6spy: true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      druid:
        filters: stat
      datasource:
        master:
          url: jdbc:mysql://192.168.1.252:3306/clinic-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: clinic-test
          password: yskj123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:sqlserver://192.168.1.252:1433;databasename=thzymzb
          username: sa
          password: yskj123456
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  redis:
    host: 192.168.1.252
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 4
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    cache:
      # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
      type: redis
    password: 123456
logging:
  level:
    com.baomidou: debug
    org.springframework.jdbc.datasource.init: debug

